providers:
  - airtap-manual
# loopback: airtap.local
browsers:
  - name: manual
  # - name: chrome
  #   version: latest
  # - name: firefox
  #   version: latest
  # - name: safari
  #   version: latest
  # - name: microsoftedge
  #   version: latest
  # - name: iphone
  #   version: latest
  # - name: manual
